### ISSUE TITLE
Make `find_venv_bin` a common function and test it

### ISSUE THREAD

**Issue by facundobatista** [facundobatista/pyempaq#10]
Note that as will be used from the unpacker, the new common module needs to be imported also from there, so needs to be "packed" in the final project.

**Comment by cacrespo** [comment]
Hi!
I'm interested in this.

**Comment by facundobatista** [comment]
The function was moved to a common place. We still need to add tests for it.

**Comment by facundobatista** [comment]
Tested in #36 . Thanks!!
