### ISSUE TITLE
Expose the .pyz path to the packaged program

### ISSUE THREAD

**Issue by fisadev** [facundobatista/pyempaq#50]
I have a program that I want to distribute as a pyempaq .pyz, but when running I want to create and use a data directory in the same location the user placed the .pyz file. So in my ,py I would need a mechanism to get the path of the .pyz from which it that was executed.

**Comment by facundobatista** [comment]
This would be `os.path.dirname(__file__)` in the script/program/module that you declared as executable, right?

**Comment by fisadev** [comment]
No, as far as I understand, because that would yield the temporary path where the files inside of the pyz are extracted. What I need is the location of the .pyz file itself (I want to store user data in the same directory of the pyz, wherever the user has decided to place it).
