### ISSUE TITLE
Support for handling the "install caches" client side

### ISSUE THREAD

**Issue by facundobatista** [facundobatista/pyempaq#59]
When the final user executes the `.pyz` a new install (virtualenv + dependencies) will be created. Running exactly the same `.pyz` will reuse that installation, but newer versions of that program, other programs, etc, all will create new installs.

So far there is nothing in the distributed `.pyz` to handle those installations (beyond running it with `PYEMPAQ_DEBUG` so the installation path is shown among other messages). We would like to have a way to handle those "install caches", for example to:

- **uninstall** a `.pyz`: this would remove all installs for the given program (all its versions, and all created by different Python versions after #58 is implemented)
- show **info** about the install cache: path location, size, maybe even a `pip freeze` of its virtualenv
- something else?

There is to be decided how these behaviours need to be triggered. @sinoroc correctly suggests that it should be part of executing the program's `.pyz` (I said that maybe we could have an extra tool, but he's right, using the same `.pyz` is more natural).

I can think of two ways to trigger these behaviours, then. Through a command line option or an environment variable (the later also suggested by @sinoroc).

- command line option: this would be through special options that have low probability on clashing with the options from the end program itself, like `python3 myprogram.pyz --pyempaq-action=uninstall`; note this is not 100% new, other systems/frameworks do the same (e.g. when running GTK-based programs you can pass `--gtk-module=module`)

- environment variable: something like `PYEMPAQ_ACTION=uninstall python3 myprogram.pyz`

In any case the end program will NOT be run, only the specific PyEmpaq action.

Other detail to consider here is that all these options are "terminal based", the user will never be able to run these functionalities by "double clicking the pyz". This is somewhat ok, for the 99% of basic cases, you'll never need to handle install caches at all. But if you want, there is a way.

**Comment by sinoroc** [comment]
I do not think the following makes sense:

> `python3 myprogram.pyz --pyempaq-action=uninstall`

How do we differentiate between arguments that are meant for the packaged program and those that are "meta arguments" meant for the packaging tool *PyEmpaq*?

**Comment by sinoroc** [comment]
> Other detail to consider here is that all these options are "terminal based", the user will never be able to run these functionalities by "double clicking the pyz". This is somewhat ok, for the 99% of basic cases, you'll never need to handle install caches at all. But if you want, there is a way.

What I have in mind with the solution I suggested (`PYEMPAQ_ACTION=uninstall python3 myprogram.pyz`), is to get the most basic but usable way to uninstall. So that if anyone asks how to uninstall, there is an answer. For sure it is not the best UX, but it should be "good enough"™. :D

Later on, for something more user friendly and powerful, there could be a dedicated standalone user-facing tool (not packager-facing, CLI or GUI).

**Comment by facundobatista** [comment]
> > 
> 
> What I have in mind with the solution I suggested (`PYEMPAQ_ACTION=uninstall python3 myprogram.pyz`), is to get the most basic but usable way to uninstall. So that if anyone asks how to uninstall, there is an answer. For sure it is not the best UX, but it should be "good enough"™. :D

+100

**Comment by sinoroc** [comment]
> > I do not think the following makes sense:
> > > `python3 myprogram.pyz --pyempaq-action=uninstall`
> > 
> > 
> > How do we differentiate between arguments that are meant for the packaged program and those that are "meta arguments" meant for the packaging tool _PyEmpaq_?
> 
> There is only one argument for PyEmpaq, `--pyempaq-action=`. There is a probability >0 of the end program to have that very same option, but is really low.

For info, both *pex* and *shiv* implement this kind of features via environment variables passed to the execution of the `.pyz`:

* https://pex.readthedocs.io/en/latest/api/vars.html
* https://shiv.readthedocs.io/en/latest/#influencing-runtime

I believe there might come a time where it will be needed to have more ways to influence the execution of the `.pyz`. For example:

* change the location where the files get unpacked:
  * `PYEMPAQ_UNPACK_PATH=/some/path python Something.pyz`.
* execute and then immediately delete:
  * `PYEMPAQ_EPHEMERAL=1 python Something.pyz`

**Comment by facundobatista** [comment]
Ah, nice information about what others use. So let's settle with environment variables!

(btw, I opened #62 and #63) for the unpack path and ephemeral ideas)
