### ISSUE TITLE
Specify exactly what to include in the project's config

### ISSUE THREAD

**Issue by facundobatista** [facundobatista/pyempaq#6]
Add a key `include` to `pyempaq.yaml` to specify what will be included in the project. It will be a list of strings, supporting wildcards, in special the double star one.

Also, add a key `ignore` to specify what to be ignored (no matter if it was included before). This is to be able to specify a whole directory or tree, but at the same time ignore temp files, `*.pyc`, etc.

Each indication line in both lists will be managed using `glob.glob(indication, recursive=True)`, [doc is here](https://docs.python.org/dev/library/glob.html#glob.glob).

Particularly, one `include` entry being `./**` means "everything in the project directory", but use with caution, you may have secrets or other files that you don't want to distribute.

Properly document this.

**Comment by cacrespo** [comment]
Hello! Please assign me this. :smile:
